@extends('layouts.app')
@section('title','Tổng quan · TaskWork') @section('heading','Tổng quan công việc')
@section('actions')<a class="btn secondary" href="{{ route('projects.create') }}">+ Project</a><a class="btn primary" href="{{ route('tasks.create') }}">+ Công việc</a>@endsection
@section('content')
<section class="stats"><article><span class="stat-icon blue">▦</span><div><small>Tổng project</small><strong>{{ $projectCount }}</strong><em>{{ $activeProjectCount }} đang chạy</em></div></article><article><span class="stat-icon violet">✓</span><div><small>Tổng công việc</small><strong>{{ $taskCount }}</strong><em>{{ $doneTaskCount }} hoàn thành</em></div></article><article><span class="stat-icon red">!</span><div><small>Quá hạn</small><strong>{{ $overdueCount }}</strong><em>Cần xử lý</em></div></article><article><span class="stat-icon green">%</span><div><small>Tiến độ chung</small><strong>{{ $taskCount ? round($doneTaskCount/$taskCount*100) : 0 }}%</strong><em>Toàn workspace</em></div></article></section>
<div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>Công việc của tôi</h2><p>Ưu tiên theo thời hạn gần nhất</p></div><a href="{{ route('tasks.index') }}">Xem tất cả →</a></div>
@forelse($myTasks as $task)<a class="task-row" href="{{ route('tasks.edit',$task) }}"><span class="priority-dot {{ $task->priority }}"></span><div class="grow"><strong>{{ $task->title }}</strong><small>{{ $task->project->key }} · {{ $task->due_date?->format('d/m/Y') ?? 'Chưa có hạn' }}</small></div><span class="badge {{ $task->status }}">{{ str_replace('_',' ',$task->status) }}</span></a>@empty<p class="empty">Bạn chưa được giao công việc nào.</p>@endforelse</section>
<section class="panel"><div class="panel-head"><div><h2>Project gần đây</h2><p>Tình hình các dự án mới nhất</p></div><a href="{{ route('projects.index') }}">Xem tất cả →</a></div>
@forelse($recentProjects as $project)<a class="project-row" href="{{ route('projects.show',$project) }}"><span class="project-key">{{ $project->key }}</span><div class="grow"><strong>{{ $project->name }}</strong><small>{{ $project->owner->name }} · {{ $project->tasks_count }} task</small></div><span class="badge {{ $project->status }}">{{ str_replace('_',' ',$project->status) }}</span></a>@empty<p class="empty">Chưa có project nào.</p>@endforelse</section></div>
@endsection
