@extends('layouts.app')
@section('title','Dự án · TaskFlow')
@section('heading','Dự án')
@section('subtitle','Theo dõi tiến độ và nguồn lực của các dự án.')
@section('actions')<a class="btn primary" href="{{ route('projects.create') }}">＋ Dự án mới</a>@endsection
@section('content')
<form class="filters"><label class="search-field">⌕<input name="search" value="{{ request('search') }}" placeholder="Tìm dự án..."></label><select name="status"><option value="">Tất cả trạng thái</option>@foreach(['planning'=>'Lên kế hoạch','active'=>'Đang chạy','on_hold'=>'Tạm dừng','completed'=>'Hoàn thành'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="btn secondary">Lọc</button></form>
<div class="project-grid">@forelse($projects as $project) @php($progress=$project->tasks_count ? round($project->done_tasks_count/$project->tasks_count*100):0)<article class="project-card"><div class="card-top"><span class="project-key">{{ $project->key }}</span><span class="badge {{ $project->status }}">{{ ['planning'=>'Lên kế hoạch','active'=>'Đang chạy','on_hold'=>'Tạm dừng','completed'=>'Hoàn thành'][$project->status] ?? $project->status }}</span></div><h2><a href="{{ route('projects.show',$project) }}">{{ $project->name }}</a></h2><p>{{ Str::limit($project->description ?: 'Chưa có mô tả cho dự án này.',100) }}</p><div class="progress"><span style="width:{{ $progress }}%"></span></div><div class="card-meta"><span>{{ $project->done_tasks_count }}/{{ $project->tasks_count }} công việc</span><b>{{ $progress }}%</b></div><div class="owner"><span class="avatar">{{ mb_substr($project->owner->name,0,1) }}</span><span>{{ $project->owner->name }}<small> · Hạn {{ $project->due_date?->format('d/m/Y') ?? '—' }}</small></span></div></article>@empty<p class="empty">Chưa tìm thấy dự án.</p>@endforelse</div>{{ $projects->links() }}
@endsection
