@extends('layouts.app')
@section('title',$project->name.' · TaskFlow')
@section('heading')<span class="project-detail-heading"><a href="{{ route('projects.index') }}"><i data-lucide="arrow-left"></i></a>{{ $project->name }}</span>@endsection
@section('subtitle'){{ $project->key }} · {{ $project->description ?: 'Chưa có mô tả cho dự án này.' }}@endsection
@section('actions')<a class="btn secondary project-edit" href="{{ route('projects.edit',$project) }}"><i data-lucide="pencil"></i>Sửa dự án</a><a class="btn primary" href="{{ route('tasks.create',['project_id'=>$project]) }}"><i data-lucide="plus"></i>Thêm task</a>@endsection
@section('content')
@php($done=$project->tasks->where('status','done')->count()) @php($progress=$project->tasks->count()?round($done/$project->tasks->count()*100):0)
<div class="project-detail-hero">
 <div class="project-detail-main"><div class="project-detail-tags"><span class="project-key">{{ $project->key }}</span><span class="badge {{ $project->status }}">{{ ['planning'=>'Lên kế hoạch','active'=>'Đang chạy','on_hold'=>'Tạm dừng','completed'=>'Hoàn thành'][$project->status]??$project->status }}</span><span class="priority {{ $project->priority }}">{{ ['urgent'=>'↑ Khẩn cấp','high'=>'↑ Cao','medium'=>'− Trung bình','low'=>'↓ Thấp'][$project->priority]??$project->priority }}</span></div><p>{{ $project->description ?: 'Chưa có mô tả cho dự án này.' }}</p><div class="project-detail-progress"><span><b>Tiến độ dự án</b><strong>{{ $progress }}%</strong></span><i><b style="width:{{ $progress }}%"></b></i><small>{{ $done }} trong {{ $project->tasks->count() }} task đã hoàn thành</small></div></div>
 <div class="project-detail-owner"><span class="avatar">{{ mb_strtoupper(mb_substr($project->owner->name,0,1)) }}</span><div><small>Chủ dự án</small><b>{{ $project->owner->name }}</b></div><div class="action-menu"><button class="action-menu-toggle" type="button"><i data-lucide="more-vertical"></i></button><div class="action-menu-popover"><a class="project-edit" href="{{ route('projects.edit',$project) }}"><i data-lucide="pencil"></i>Chỉnh sửa</a><button type="button" data-delete-action="{{ route('projects.destroy',$project) }}" data-delete-message="Xóa dự án và toàn bộ task bên trong?"><i data-lucide="trash-2"></i>Xóa dự án</button></div></div></div>
</div>
<section class="project-detail-stats">@foreach([['list-checks','Tổng task',$project->tasks->count(),'blue'],['circle-dot','Cần làm',$project->tasks->where('status','todo')->count(),'slate'],['loader-circle','Đang thực hiện',$project->tasks->where('status','in_progress')->count(),'orange'],['scan-eye','Đang review',$project->tasks->where('status','review')->count(),'violet'],['circle-check-big','Hoàn thành',$done,'green']] as [$icon,$label,$value,$color])<article><span class="mine-stat-icon {{ $color }}"><i data-lucide="{{ $icon }}"></i></span><div><small>{{ $label }}</small><strong>{{ $value }}</strong></div></article>@endforeach</section>
<nav class="project-detail-tabs"><a class="active" href="#tasks">Danh sách task <span>{{ $project->tasks->count() }}</span></a><a href="#information">Thông tin dự án</a><a href="#members">Thành viên <span>{{ $project->members->count() }}</span></a></nav>
<div class="project-detail-layout">
 <section class="panel project-detail-tasks" id="tasks"><header><div><h2>Danh sách task</h2><p>Theo dõi công việc thuộc dự án này.</p></div><a class="btn primary" href="{{ route('tasks.create',['project_id'=>$project]) }}"><i data-lucide="plus"></i>Thêm task</a></header><div class="table-wrap"><table><thead><tr><th>Task</th><th>Người thực hiện</th><th>Ưu tiên</th><th>Trạng thái</th><th>Thời hạn</th><th></th></tr></thead><tbody>@forelse($project->tasks->sortByDesc('created_at') as $task)<tr><td><a class="task-title-link" href="{{ route('tasks.edit',$task) }}"><b>{{ $task->title }}</b><small>{{ Str::limit($task->description,55) }}</small></a></td><td><span class="person"><span class="avatar">{{ mb_strtoupper(mb_substr($task->assignee?->name??'?',0,1)) }}</span>{{ $task->assignee?->name??'Chưa giao' }}</span></td><td><span class="priority {{ $task->priority }}">{{ ['urgent'=>'↑ Khẩn cấp','high'=>'↑ Cao','medium'=>'− Trung bình','low'=>'↓ Thấp'][$task->priority] }}</span></td><td><span class="badge {{ $task->status }}">{{ ['todo'=>'Cần làm','in_progress'=>'Đang thực hiện','review'=>'Đang review','done'=>'Hoàn thành'][$task->status] }}</span></td><td class="{{ $task->due_date?->isPast()&&$task->status!=='done'?'text-danger':'' }}">{{ $task->due_date?->format('d/m/Y')??'—' }}</td><td>@include('tasks.partials.actions',['task'=>$task])</td></tr>@empty<tr><td colspan="6"><div class="project-task-empty"><i data-lucide="clipboard-list"></i><b>Chưa có task</b><span>Thêm công việc đầu tiên cho dự án.</span></div></td></tr>@endforelse</tbody></table></div></section>
 <aside class="project-detail-side"><section class="panel" id="information"><h2>Thông tin dự án</h2><dl><div><dt><i data-lucide="calendar-days"></i>Bắt đầu</dt><dd>{{ $project->start_date?->format('d/m/Y')??'Chưa đặt' }}</dd></div><div><dt><i data-lucide="flag"></i>Hạn hoàn thành</dt><dd class="{{ $project->due_date?->isPast()&&$project->status!=='completed'?'text-danger':'' }}">{{ $project->due_date?->format('d/m/Y')??'Chưa đặt' }}</dd></div><div><dt><i data-lucide="activity"></i>Trạng thái</dt><dd>{{ ['planning'=>'Lên kế hoạch','active'=>'Đang chạy','on_hold'=>'Tạm dừng','completed'=>'Hoàn thành'][$project->status]??$project->status }}</dd></div></dl></section><section class="panel" id="members"><div class="side-card-head"><h2>Thành viên</h2><b>{{ $project->members->count() }}</b></div><div class="project-member-list">@forelse($project->members as $member)<div><span class="avatar">{{ mb_strtoupper(mb_substr($member->name,0,1)) }}</span><span><b>{{ $member->name }}</b><small>{{ $member->email }}</small></span></div>@empty<p>Chưa có thành viên.</p>@endforelse</div></section></aside>
</div>
@include('tasks.partials.modal')
@include('projects.partials.modal')
@endsection
