@extends('layouts.app')
@section('title', 'Nhãn · TaskFlow')
@section('heading') Nhãn <span class="heading-count">{{ $tabCounts['all'] }}</span> @endsection
@section('subtitle', 'Tổ chức công việc bằng các nhãn tùy chỉnh.')
@section('content')
<div class="label-toolbar">
 <form method="GET" class="label-search"><input type="hidden" name="type" value="{{ $type }}"><i data-lucide="search"></i><input name="search" value="{{ request('search') }}" placeholder="Tìm kiếm nhãn...">@if(request('search'))<a href="{{ route('labels',['type'=>$type]) }}"><i data-lucide="x"></i></a>@endif</form>
 <button class="btn primary" type="button" data-label-create><i data-lucide="plus"></i>Tạo nhãn mới</button>
</div>
<nav class="label-tabs">
 @foreach(['all'=>'Tất cả','system'=>'Nhãn hệ thống','mine'=>'Tạo bởi tôi','archived'=>'Đã lưu trữ'] as $key=>$name)<a class="{{ $type===$key?'active':'' }}" href="{{ route('labels',array_filter(['type'=>$key,'search'=>request('search')])) }}">{{ $name }} <span>{{ $tabCounts[$key] }}</span></a>@endforeach
</nav>
<div class="label-layout">
 <section class="panel label-table-card"><div class="table-wrap"><table class="label-table"><thead><tr><th>Nhãn</th><th>Màu sắc</th><th>Mô tả</th><th>Số task</th><th>Tạo bởi</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>
 @forelse($labels as $label)<tr>
  <td><span class="label-name" style="--label-color:{{ $label->color }}"><i></i>{{ $label->name }}</span></td><td><span class="label-color"><i style="background:{{ $label->color }}"></i>{{ strtoupper($label->color) }}</span></td><td class="label-description">{{ $label->description?:'—' }}</td><td><strong>{{ $label->tasks_count }}</strong> task</td>
  <td><span class="label-creator">@if($label->creator)<span class="avatar small">{{ mb_strtoupper(mb_substr($label->creator->name,0,1)) }}</span>{{ $label->creator->name }}@else<span class="system-avatar"><i data-lucide="settings-2"></i></span>Hệ thống @endif</span></td><td>{{ $label->created_at->format('d/m/Y') }}</td>
  <td><div class="action-menu"><button class="action-menu-toggle" type="button" aria-label="Thao tác" aria-expanded="false"><i data-lucide="more-vertical"></i></button><div class="action-menu-popover"><button type="button" data-label-edit data-action="{{ route('labels.update',$label) }}" data-name="{{ $label->name }}" data-color="{{ $label->color }}" data-description="{{ $label->description }}" data-archived="{{ (int)$label->is_archived }}"><i data-lucide="pencil"></i>Chỉnh sửa</button><button type="button" data-delete-action="{{ route('labels.destroy',$label) }}" data-delete-message="Xóa nhãn ‘{{ $label->name }}’? Nhãn sẽ được gỡ khỏi các task."><i data-lucide="trash-2"></i>Xóa nhãn</button></div></div></td>
 </tr>@empty<tr><td colspan="7"><div class="label-empty"><i data-lucide="tags"></i><strong>Không tìm thấy nhãn</strong><span>Thử từ khóa khác hoặc tạo một nhãn mới.</span></div></td></tr>@endforelse
 </tbody></table></div><div class="label-pagination"><span>Hiển thị {{ $labels->firstItem()??0 }}–{{ $labels->lastItem()??0 }} trong {{ $labels->total() }} nhãn</span><div>{{ $labels->onEachSide(1)->links() }}</div></div></section>
 <aside class="label-side">
  <section class="panel label-stats-card"><h2>Thống kê nhãn</h2><div class="label-donut"><span><strong>{{ $tabCounts['all'] }}</strong>Nhãn</span></div><div class="label-stat-lines"><div><span>Tổng số nhãn</span><strong>{{ $tabCounts['all']+$tabCounts['archived'] }}</strong></div><div><span>Nhãn hệ thống</span><strong>{{ $tabCounts['system'] }}</strong></div><div><span>Nhãn của bạn</span><strong>{{ $tabCounts['mine'] }}</strong></div></div></section>
  <section class="panel label-popular-card"><h2>Nhãn được dùng nhiều</h2>@forelse($popularLabels as $label)<div class="label-rank"><span class="label-name" style="--label-color:{{ $label->color }}"><i></i>{{ $label->name }}</span><strong>{{ $label->tasks_count }}</strong></div>@empty<p>Chưa có dữ liệu.</p>@endforelse</section>
  <section class="panel label-manage-card"><h2>Quản lý nhãn</h2><button type="button" data-label-create><span><i data-lucide="plus-circle"></i><b>Tạo nhãn mới</b></span><i data-lucide="chevron-right"></i></button><a href="{{ route('labels',['type'=>'system']) }}"><span><i data-lucide="settings-2"></i><b>Nhãn hệ thống</b></span><i data-lucide="chevron-right"></i></a><a href="{{ route('labels',['type'=>'archived']) }}"><span><i data-lucide="archive"></i><b>Nhãn đã lưu trữ</b></span><i data-lucide="chevron-right"></i></a></section>
 </aside>
</div>
<dialog class="app-modal" id="label-modal"><div class="modal-card"><div class="modal-head"><div><h2>Tạo nhãn mới</h2><p>Dùng nhãn để phân loại công việc nhanh hơn.</p></div><button type="button" data-label-close><i data-lucide="x"></i></button></div><form method="POST" action="{{ route('labels.store') }}">@csrf<div class="modal-body label-form"><label>Tên nhãn<input name="name" required maxlength="80" placeholder="Ví dụ: Khách hàng"></label><label>Màu sắc<div class="color-input"><input type="color" name="color" value="#315cf4"><span>#315CF4</span></div></label><label>Mô tả<textarea name="description" rows="3" maxlength="255"></textarea></label></div><div class="modal-actions"><button class="btn secondary" type="button" data-label-close>Hủy</button><button class="btn primary" type="submit">Tạo nhãn</button></div></form></div></dialog>
<dialog class="app-modal" id="label-edit-modal"><div class="modal-card"><div class="modal-head"><div><h2>Chỉnh sửa nhãn</h2><p>Cập nhật nội dung và trạng thái nhãn.</p></div><button type="button" data-label-edit-close><i data-lucide="x"></i></button></div><form method="POST">@csrf @method('PUT')<div class="modal-body label-form"><label>Tên nhãn<input name="name" required maxlength="80"></label><label>Màu sắc<div class="color-input"><input type="color" name="color"><span></span></div></label><label>Mô tả<textarea name="description" rows="3" maxlength="255"></textarea></label><label class="archive-option"><input type="hidden" name="is_archived" value="0"><input type="checkbox" name="is_archived" value="1"><span><b>Lưu trữ nhãn</b><small>Ẩn nhãn khỏi danh sách sử dụng.</small></span></label></div><div class="modal-actions"><button class="btn secondary" type="button" data-label-edit-close>Hủy</button><button class="btn primary" type="submit">Lưu thay đổi</button></div></form></div></dialog>
@endsection
