@extends('layouts.app')
@section('title','Báo cáo · TaskFlow')
@section('heading','Báo cáo')
@section('actions')@endsection
@section('content')
@php
    $total=$tasks->count(); $done=$tasks->where('status','done')->count(); $doing=$tasks->where('status','in_progress')->count(); $review=$tasks->where('status','review')->count(); $todo=$tasks->where('status','todo')->count();
    $overdue=$tasks->filter(fn($task)=>$task->due_date?->isPast()&&$task->status!=='done')->count(); $rate=$total?round($done/$total*100):0;
    $previousTotal=$previousTasks->count(); $previousDone=$previousTasks->where('status','done')->count(); $previousRate=$previousTotal?round($previousDone/$previousTotal*100):0;
    $change=$previousTotal?round(($total-$previousTotal)/$previousTotal*100):($total?100:0); $rateChange=$rate-$previousRate;
    $maxTrend=max(1,$trend->max('total')); $chartPoints=$trend->values()->map(fn($point,$i)=>(45+$i*105).','. (185-$point['total']/$maxTrend*135))->implode(' '); $donePoints=$trend->values()->map(fn($point,$i)=>(45+$i*105).','. (185-$point['done']/$maxTrend*135))->implode(' ');
@endphp
<div class="report-toolbar"><nav><a class="active">Tổng quan</a><a href="#project-report">Dự án</a><a href="#member-report">Thành viên</a><a href="{{ route('tasks.index') }}">Task</a></nav><form method="get"><select name="days" data-auto-submit>@foreach([7=>'7 ngày qua',30=>'30 ngày qua',90=>'90 ngày qua'] as $value=>$label)<option value="{{ $value }}" @selected($days===$value)>{{ $label }}</option>@endforeach</select></form><button class="btn secondary" type="button" data-report-export><i data-lucide="download"></i>Xuất báo cáo</button></div>
<section class="report-metrics">
@foreach([['Tổng task',$total,'calendar-days','blue',$change],['Hoàn thành',$done,'circle-check-big','green',$rateChange],['Đang thực hiện',$doing,'clock-3','orange',0],['Hiệu suất hoàn thành',$rate.'%','activity','violet',$rateChange],['Task quá hạn',$overdue,'circle-alert','red',0]] as [$label,$value,$icon,$color,$delta])<article><span class="report-metric-icon {{ $color }}"><i data-lucide="{{ $icon }}"></i></span><div><small>{{ $label }}</small><strong>{{ $value }}</strong><em class="{{ $delta<0?'down':'up' }}">{{ $delta>=0?'↑':'↓' }} {{ abs($delta) }}% <span>so với kỳ trước</span></em></div></article>@endforeach
</section>
<div class="report-primary-grid"><section class="report-card report-trend"><header><div><h2>Xu hướng hoàn thành task</h2><p>Dữ liệu 7 ngày gần nhất trong kỳ</p></div><span>Theo ngày</span></header><div class="trend-legend"><i class="total"></i>Tổng task <i class="done"></i>Hoàn thành</div><svg viewBox="0 0 720 220" role="img" aria-label="Biểu đồ xu hướng">@foreach(range(0,4) as $line)<line x1="40" y1="{{ 50+$line*34 }}" x2="690" y2="{{ 50+$line*34 }}" class="grid-line"/>@endforeach<polyline points="{{ $chartPoints }}" class="trend-total"/><polyline points="{{ $donePoints }}" class="trend-done"/>@foreach($trend as $i=>$point)<circle cx="{{ 45+$i*105 }}" cy="{{ 185-$point['total']/$maxTrend*135 }}" r="4" class="point-total"/><circle cx="{{ 45+$i*105 }}" cy="{{ 185-$point['done']/$maxTrend*135 }}" r="4" class="point-done"/><text x="{{ 45+$i*105 }}" y="210">{{ $point['date'] }}</text>@endforeach</svg></section>
<section class="report-card status-distribution"><header><div><h2>Phân bổ task theo trạng thái</h2><p>Tổng {{ $total }} công việc</p></div></header><div class="distribution-body"><div class="report-donut" style="--todo:{{ $total?$todo/$total*100:0 }}%;--doing:{{ $total?($todo+$doing)/$total*100:0 }}%;--review:{{ $total?($todo+$doing+$review)/$total*100:0 }}%"><span><b>{{ $total }}</b>Tổng</span></div><div class="distribution-list">@foreach([['Việc cần làm',$todo,'slate'],['Đang thực hiện',$doing,'blue'],['Đang review',$review,'orange'],['Hoàn thành',$done,'green'],['Quá hạn',$overdue,'red']] as [$label,$count,$color])<p><i class="{{ $color }}"></i><span>{{ $label }}</span><b>{{ $count }} <small>({{ $total?round($count/$total*100):0 }}%)</small></b></p>@endforeach</div></div></section></div>
<div class="report-secondary-grid"><section class="report-card" id="project-report"><header><h2>Phân bổ task theo dự án</h2></header><div class="project-report-list">@foreach($projects->sortByDesc('tasks_count')->take(6) as $project)<div><span><i style="background:#{{ substr(md5($project->key),0,6) }}"></i>{{ Str::limit($project->name,22) }}</span><b><i style="width:{{ $projects->max('tasks_count')?$project->tasks_count/$projects->max('tasks_count')*100:0 }}%"></i></b><em>{{ $project->tasks_count }}</em></div>@endforeach</div></section>
<section class="report-card" id="member-report"><header><h2>Hiệu suất theo thành viên</h2></header><div class="member-report-list">@foreach($members->sortByDesc('done_count')->take(5) as $member)@php($memberRate=$member->tasks_count?round($member->done_count/$member->tasks_count*100):0)<div><span class="avatar">{{ mb_substr($member->name,0,1) }}</span><span><b>{{ $member->name }}</b><small>{{ $member->done_count }}/{{ $member->tasks_count }} hoàn thành</small></span><i><b style="width:{{ $memberRate }}%"></b></i><strong>{{ $memberRate }}%</strong></div>@endforeach</div></section>
<section class="report-card"><header><h2>Task quá hạn theo dự án</h2><a href="{{ route('tasks.index',['overdue'=>1]) }}">Xem chi tiết</a></header><div class="overdue-report-list">@foreach($projects->take(6) as $project)@php($count=$tasks->where('project_id',$project->id)->filter(fn($task)=>$task->due_date?->isPast()&&$task->status!=='done')->count())<div><span>{{ Str::limit($project->name,18) }}</span><i><b style="width:{{ $overdue?max(8,$count/$overdue*100):0 }}%"></b></i><strong>{{ $count }}</strong></div>@endforeach</div></section></div>
@endsection
