@extends('layouts.app')
@section('title','Cài đặt · TaskFlow') @section('heading','Cài đặt')
@section('content')
@php($prefs=auth()->user()->preferences??['theme'=>'light','density'=>'standard','show_task_count'=>true,'notification_sound'=>true,'auto_save'=>true,'fullscreen_task'=>false])
<div class="settings-layout">
 <aside class="settings-nav"><h4>CÀI ĐẶT</h4><a href="#profile" class="active" data-settings-link><i data-lucide="user-round"></i>Hồ sơ cá nhân</a><a href="#account" data-settings-link><i data-lucide="circle-user-round"></i>Tài khoản</a><a href="#notifications" data-settings-link><i data-lucide="bell"></i>Thông báo</a><a href="#appearance" data-settings-link><i data-lucide="palette"></i>Giao diện</a><a href="#time-management" data-settings-link><i data-lucide="clock-3"></i>Quản lý thời gian</a><a href="#security" data-settings-link><i data-lucide="shield-check"></i>Bảo mật</a><a href="#backup" data-settings-link><i data-lucide="cloud"></i>Sao lưu & Đồng bộ</a><a href="#integrations" data-settings-link><i data-lucide="plug"></i>Tích hợp</a><a href="{{ route('members') }}"><i data-lucide="users-round"></i>Nhóm & Quyền hạn</a><a href="#custom-fields" data-settings-link><i data-lucide="panels-top-left"></i>Trường tùy chỉnh</a><a href="{{ route('labels') }}"><i data-lucide="tag"></i>Nhãn mặc định</a><a href="#task-templates" data-settings-link><i data-lucide="clipboard-list"></i>Mẫu task</a><a href="#trash" data-settings-link><i data-lucide="trash-2"></i>Thùng rác</a></aside>
 <main class="settings-content"><header class="settings-title"><h2>Hồ sơ cá nhân</h2><p>Quản lý thông tin cá nhân và tùy chỉnh tài khoản của bạn.</p></header>
  <div class="settings-main-grid">
   <section class="settings-card profile-settings" id="profile"><h3>Thông tin cá nhân</h3><form method="POST" action="{{ route('settings.profile') }}">@csrf @method('PUT')<div class="settings-profile-body"><div class="profile-photo"><span class="avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span><button class="btn secondary" type="button"><i data-lucide="camera"></i>Thay đổi ảnh</button></div><div class="settings-fields"><label>Họ và tên<input name="name" value="{{ old('name',auth()->user()->name) }}" required></label><label>Email<input type="email" name="email" value="{{ old('email',auth()->user()->email) }}" required></label><div class="two-fields"><label>Số điện thoại<input name="phone" value="{{ old('phone',auth()->user()->phone) }}" placeholder="0123 456 789"></label><label>Chức danh<input name="job_title" value="{{ old('job_title',auth()->user()->job_title) }}" placeholder="Quản trị viên"></label></div><label>Múi giờ<select name="timezone"><option value="Asia/Ho_Chi_Minh" @selected(auth()->user()->timezone==='Asia/Ho_Chi_Minh')>(GMT+07:00) Bangkok, Hanoi, Jakarta</option><option value="Asia/Bangkok">(GMT+07:00) Bangkok</option><option value="UTC">(GMT+00:00) UTC</option></select></label><label>Ngôn ngữ<select name="locale"><option value="vi" @selected(auth()->user()->locale==='vi')>Tiếng Việt</option><option value="en" @selected(auth()->user()->locale==='en')>English</option></select></label><label>Giới thiệu bản thân<textarea name="bio" rows="3" placeholder="Một vài dòng về bạn...">{{ old('bio',auth()->user()->bio) }}</textarea></label><div class="settings-save"><button class="btn primary"><i data-lucide="save"></i>Lưu thay đổi</button></div></div></div></form></section>
   <section class="settings-card preference-settings"><h3>Tùy chọn cá nhân</h3><form method="POST" action="{{ route('settings.preferences') }}">@csrf @method('PUT')<label>Giao diện</label><div class="theme-options">@foreach([['light','sun','Sáng'],['dark','moon','Tối'],['system','monitor','Hệ thống']] as [$value,$icon,$name])<label><input type="radio" name="theme" value="{{ $value }}" @checked(($prefs['theme']??'light')===$value)><span><i data-lucide="{{ $icon }}"></i>{{ $name }}</span></label>@endforeach</div><label>Mật độ hiển thị<small>Điều chỉnh mật độ hiển thị của giao diện</small><select name="density"><option value="compact">Thu gọn</option><option value="standard" @selected(($prefs['density']??'standard')==='standard')>Tiêu chuẩn</option><option value="comfortable">Thoải mái</option></select></label>@foreach([['show_task_count','Hiển thị số lượng task trên menu','Hiển thị số lượng task ở mỗi mục trong menu'],['notification_sound','Phát âm thanh thông báo','Phát âm thanh khi có thông báo mới'],['auto_save','Tự động lưu','Tự động lưu thay đổi trong quá trình làm việc'],['fullscreen_task','Mở task mới ở chế độ toàn màn hình','Hiển thị chi tiết task ở chế độ toàn màn hình']] as [$key,$title,$note])<label class="setting-switch"><span><b>{{ $title }}</b><small>{{ $note }}</small></span><input type="checkbox" name="{{ $key }}" value="1" @checked($prefs[$key]??false)><i></i></label>@endforeach<div class="settings-save"><button class="btn primary"><i data-lucide="save"></i>Lưu tùy chọn</button></div></form></section>
  </div>
  <div class="settings-bottom-grid">
   <section class="settings-card password-settings"><h3>Đổi mật khẩu</h3><form method="POST" action="{{ route('settings.password') }}">@csrf @method('PUT')<label>Mật khẩu hiện tại<div class="password-field"><input type="password" name="current_password" required><button type="button" data-password-toggle><i data-lucide="eye-off"></i></button></div></label><label>Mật khẩu mới<div class="password-field"><input type="password" name="password" required minlength="8"><button type="button" data-password-toggle><i data-lucide="eye-off"></i></button></div></label><label>Xác nhận mật khẩu mới<div class="password-field"><input type="password" name="password_confirmation" required><button type="button" data-password-toggle><i data-lucide="eye-off"></i></button></div></label><button class="btn secondary">Đổi mật khẩu</button></form></section>
   <section class="settings-card session-settings"><div class="card-heading"><div><h3>Phiên đăng nhập</h3><p>Quản lý các thiết bị đã đăng nhập vào tài khoản của bạn.</p></div></div>@forelse($sessions->take(3) as $session)<div class="session-row"><span><i data-lucide="{{ str_contains(strtolower($session->user_agent??''),'mobile')?'smartphone':'monitor' }}"></i></span><div><b>{{ str_contains($session->user_agent??'','Windows')?'Windows':'Thiết bị' }} · Trình duyệt</b><small>{{ $session->ip_address }} @if(session()->getId()===$session->id)<em>Thiết bị hiện tại</em>@endif</small></div><time>{{ session()->getId()===$session->id?'Hiện tại':\Carbon\Carbon::createFromTimestamp($session->last_activity)->diffForHumans() }}</time></div>@empty<div class="session-row"><span><i data-lucide="monitor"></i></span><div><b>Thiết bị hiện tại</b><small>Phiên đăng nhập đang hoạt động</small></div><time>Hiện tại</time></div>@endforelse</section>
  </div>
  <section class="settings-tools-grid" id="account"><article class="settings-card" id="backup"><span class="settings-tool-icon"><i data-lucide="download"></i></span><div><h3>Sao lưu dữ liệu tài khoản</h3><p>Tải hồ sơ và tùy chọn của bạn dưới dạng JSON.</p></div><a class="btn secondary" href="{{ route('settings.export') }}"><i data-lucide="download"></i>Tải bản sao</a></article><article class="settings-card" id="integrations"><span class="settings-tool-icon"><i data-lucide="github"></i></span><div><h3>Tích hợp</h3><p>Quản lý kết nối dịch vụ ngoài của workspace.</p></div><span class="status-badge">Chưa kết nối</span></article><article class="settings-card" id="custom-fields"><span class="settings-tool-icon"><i data-lucide="panels-top-left"></i></span><div><h3>Trường tùy chỉnh</h3><p>Quản lý trường dữ liệu bổ sung cho task.</p></div><a class="btn secondary" href="{{ route('tasks.index') }}">Quản lý task</a></article><article class="settings-card" id="task-templates"><span class="settings-tool-icon"><i data-lucide="clipboard-list"></i></span><div><h3>Mẫu task</h3><p>Tạo task mới và dùng lại cấu trúc công việc.</p></div><a class="btn secondary" href="{{ route('tasks.create') }}">Tạo task</a></article><article class="settings-card" id="trash"><span class="settings-tool-icon danger"><i data-lucide="trash-2"></i></span><div><h3>Thùng rác</h3><p>Dữ liệu đang được xóa vĩnh viễn; chưa có mục nào trong thùng rác.</p></div><span class="status-badge">0 mục</span></article></section>
  <section class="settings-card zalo-integration-card" id="zalo-integration">
   <div class="card-heading"><div><h3>Tích hợp Zalo Bot</h3><p>Nhận thông báo task trong nhóm chung và cuộc trò chuyện Zalo cá nhân.</p></div><span class="status-badge">{{ config('services.zalo_bot.token') ? 'Đã cấu hình' : 'Chưa cấu hình' }}</span></div>
   <div class="settings-main-grid">
    <div><h4>Zalo cá nhân</h4>@if(auth()->user()->zalo_chat_id)<p>Đã liên kết với chat ID <b>{{ Str::mask(auth()->user()->zalo_chat_id,'*',4,-4) }}</b>.</p><form method="POST" action="{{ route('settings.zalo.unlink') }}">@csrf @method('DELETE')<button class="btn secondary"><i data-lucide="unlink"></i>Ngắt liên kết</button></form>@else<p>Nhắn nội dung sau cho Bot để liên kết tài khoản:</p><code>/link {{ auth()->user()->zalo_link_code }}</code><a class="btn secondary" href="https://zalo.me/s/botcreator/" target="_blank" rel="noopener"><i data-lucide="message-circle"></i>Mở Zalo Bot</a>@endif</div>
    <div><h4>Nhóm Zalo chung</h4>@if(auth()->user()->role==='admin')<p>Mời Bot vào nhóm và nhắc @Bot một lần để nhóm xuất hiện tại đây.</p><form method="POST" action="{{ route('settings.zalo.group') }}">@csrf @method('PUT')<select name="chat_id"><option value="">Không gửi vào nhóm</option>@foreach($zaloChats->where('chat_type','GROUP') as $chat)<option value="{{ $chat->chat_id }}" @selected($chat->is_group_target)>{{ $chat->display_name ?: 'Nhóm '.$chat->chat_id }}</option>@endforeach</select><button class="btn primary"><i data-lucide="save"></i>Lưu nhóm</button></form><a href="https://bot.zaloplatforms.com/groups/invite/bot.sJxDUGyk" target="_blank" rel="noopener">Mời Bot vào nhóm Zalo</a>@else<p>{{ $zaloChats->contains('is_group_target',true) ? 'Quản trị viên đã cấu hình nhóm nhận thông báo.' : 'Chưa cấu hình nhóm nhận thông báo.' }}</p>@endif</div>
   </div>
  </section>
 </main>
</div>
@endsection
