@extends('layouts.app')
@section('title','Cài đặt · TaskFlow') @section('heading','Cài đặt')
@section('content')
@php($prefs=auth()->user()->preferences??['theme'=>'light','density'=>'standard','show_task_count'=>true,'notification_sound'=>true,'auto_save'=>true,'fullscreen_task'=>false])
<div class="settings-layout">
 <aside class="settings-nav"><h4>CÀI ĐẶT</h4>@foreach([['user-round','Hồ sơ cá nhân',true],['circle-user-round','Tài khoản',false],['bell','Thông báo',false],['palette','Giao diện',false],['clock-3','Quản lý thời gian',false],['shield-check','Bảo mật',false],['cloud','Sao lưu & Đồng bộ',false],['plug','Tích hợp',false],['users-round','Nhóm & Quyền hạn',false],['panels-top-left','Trường tùy chỉnh',false],['tag','Nhãn mặc định',false],['clipboard-list','Mẫu task',false],['trash-2','Thùng rác',false]] as [$icon,$label,$active])<a href="#{{ $active?'profile':'!' }}" class="{{ $active?'active':'' }}"><i data-lucide="{{ $icon }}"></i>{{ $label }}</a>@endforeach</aside>
 <main class="settings-content"><header class="settings-title"><h2>Hồ sơ cá nhân</h2><p>Quản lý thông tin cá nhân và tùy chỉnh tài khoản của bạn.</p></header>
  <div class="settings-main-grid">
   <section class="settings-card profile-settings" id="profile"><h3>Thông tin cá nhân</h3><form method="POST" action="{{ route('settings.profile') }}">@csrf @method('PUT')<div class="settings-profile-body"><div class="profile-photo"><span class="avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span><button class="btn secondary" type="button"><i data-lucide="camera"></i>Thay đổi ảnh</button></div><div class="settings-fields"><label>Họ và tên<input name="name" value="{{ old('name',auth()->user()->name) }}" required></label><label>Email<input type="email" name="email" value="{{ old('email',auth()->user()->email) }}" required></label><div class="two-fields"><label>Số điện thoại<input name="phone" value="{{ old('phone',auth()->user()->phone) }}" placeholder="0123 456 789"></label><label>Chức danh<input name="job_title" value="{{ old('job_title',auth()->user()->job_title) }}" placeholder="Quản trị viên"></label></div><label>Múi giờ<select name="timezone"><option value="Asia/Ho_Chi_Minh" @selected(auth()->user()->timezone==='Asia/Ho_Chi_Minh')>(GMT+07:00) Bangkok, Hanoi, Jakarta</option><option value="Asia/Bangkok">(GMT+07:00) Bangkok</option><option value="UTC">(GMT+00:00) UTC</option></select></label><label>Ngôn ngữ<select name="locale"><option value="vi" @selected(auth()->user()->locale==='vi')>Tiếng Việt</option><option value="en" @selected(auth()->user()->locale==='en')>English</option></select></label><label>Giới thiệu bản thân<textarea name="bio" rows="3" placeholder="Một vài dòng về bạn...">{{ old('bio',auth()->user()->bio) }}</textarea></label><div class="settings-save"><button class="btn primary"><i data-lucide="save"></i>Lưu thay đổi</button></div></div></div></form></section>
   <section class="settings-card preference-settings"><h3>Tùy chọn cá nhân</h3><form method="POST" action="{{ route('settings.preferences') }}">@csrf @method('PUT')<label>Giao diện</label><div class="theme-options">@foreach([['light','sun','Sáng'],['dark','moon','Tối'],['system','monitor','Hệ thống']] as [$value,$icon,$name])<label><input type="radio" name="theme" value="{{ $value }}" @checked(($prefs['theme']??'light')===$value)><span><i data-lucide="{{ $icon }}"></i>{{ $name }}</span></label>@endforeach</div><label>Mật độ hiển thị<small>Điều chỉnh mật độ hiển thị của giao diện</small><select name="density"><option value="compact">Thu gọn</option><option value="standard" @selected(($prefs['density']??'standard')==='standard')>Tiêu chuẩn</option><option value="comfortable">Thoải mái</option></select></label>@foreach([['show_task_count','Hiển thị số lượng task trên menu','Hiển thị số lượng task ở mỗi mục trong menu'],['notification_sound','Phát âm thanh thông báo','Phát âm thanh khi có thông báo mới'],['auto_save','Tự động lưu','Tự động lưu thay đổi trong quá trình làm việc'],['fullscreen_task','Mở task mới ở chế độ toàn màn hình','Hiển thị chi tiết task ở chế độ toàn màn hình']] as [$key,$title,$note])<label class="setting-switch"><span><b>{{ $title }}</b><small>{{ $note }}</small></span><input type="checkbox" name="{{ $key }}" value="1" @checked($prefs[$key]??false)><i></i></label>@endforeach<div class="settings-save"><button class="btn primary"><i data-lucide="save"></i>Lưu tùy chọn</button></div></form></section>
  </div>
  <div class="settings-bottom-grid">
   <section class="settings-card password-settings"><h3>Đổi mật khẩu</h3><form method="POST" action="{{ route('settings.password') }}">@csrf @method('PUT')<label>Mật khẩu hiện tại<div class="password-field"><input type="password" name="current_password" required><button type="button" data-password-toggle><i data-lucide="eye-off"></i></button></div></label><label>Mật khẩu mới<div class="password-field"><input type="password" name="password" required minlength="8"><button type="button" data-password-toggle><i data-lucide="eye-off"></i></button></div></label><label>Xác nhận mật khẩu mới<div class="password-field"><input type="password" name="password_confirmation" required><button type="button" data-password-toggle><i data-lucide="eye-off"></i></button></div></label><button class="btn secondary">Đổi mật khẩu</button></form></section>
   <section class="settings-card session-settings"><div class="card-heading"><div><h3>Phiên đăng nhập</h3><p>Quản lý các thiết bị đã đăng nhập vào tài khoản của bạn.</p></div></div>@forelse($sessions->take(3) as $session)<div class="session-row"><span><i data-lucide="{{ str_contains(strtolower($session->user_agent??''),'mobile')?'smartphone':'monitor' }}"></i></span><div><b>{{ str_contains($session->user_agent??'','Windows')?'Windows':'Thiết bị' }} · Trình duyệt</b><small>{{ $session->ip_address }} @if(session()->getId()===$session->id)<em>Thiết bị hiện tại</em>@endif</small></div><time>{{ session()->getId()===$session->id?'Hiện tại':\Carbon\Carbon::createFromTimestamp($session->last_activity)->diffForHumans() }}</time></div>@empty<div class="session-row"><span><i data-lucide="monitor"></i></span><div><b>Thiết bị hiện tại</b><small>Phiên đăng nhập đang hoạt động</small></div><time>Hiện tại</time></div>@endforelse</section>
  </div>
 </main>
</div>
@endsection
