import { chromium } from 'playwright-core';

const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' });
const page = await browser.newPage({ viewport: { width: 1536, height: 1024 }, deviceScaleFactor: 1 });
await page.goto('http://127.0.0.1:8000/login');
await page.locator('input[name="email"]').fill('admin@taskwork.local');
await page.locator('input[name="password"]').fill('ChangeMe123!');
await Promise.all([page.waitForURL('**/dashboard'), page.locator('.login-submit').click()]);
for (const [name, path] of Object.entries({ dashboard: '/dashboard', 'task-cua-toi': '/my-tasks', 'tat-ca-task': '/tasks', 'du-an': '/projects', lich: '/calendar', 'bao-cao': '/reports', 'thanh-vien': '/members', nhan: '/labels', 'cai-dat': '/settings' })) {
    await page.goto(`http://127.0.0.1:8000${path}`);
    await page.screenshot({ path: `storage/app/${name}-current.png`, fullPage: false });
}
await page.goto('http://127.0.0.1:8000/calendar?view=month');
await page.locator('.month-calendar').waitFor({ state: 'visible' });
await page.goto('http://127.0.0.1:8000/calendar?view=agenda');
await page.locator('.calendar-agenda').waitFor({ state: 'visible' });
await page.goto('http://127.0.0.1:8000/tasks');
await page.goto('http://127.0.0.1:8000/tasks?view=kanban');
if (await page.locator('.kanban-column').count() !== 4) throw new Error('Kanban columns are missing');
await page.screenshot({ path: 'storage/app/task-kanban-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/tasks?view=gantt');
await page.locator('.task-gantt').waitFor({ state: 'visible' });
await page.screenshot({ path: 'storage/app/task-gantt-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/tasks?search=dashboard');
await page.locator('.search-reset').click();
await page.waitForURL((url) => !url.searchParams.has('search'));
await page.goto('http://127.0.0.1:8000/tasks');
await page.locator('[data-filter-toggle]').click();
await page.locator('.task-filter-form.open').waitFor({ state: 'visible' });
await page.screenshot({ path: 'storage/app/task-filter-current.png', fullPage: false });
const unfilteredTotal = Number(await page.locator('.summary-card.all b').textContent());
await page.locator('.task-filter-form select[name="project_id"]').selectOption({ index: 1 });
await Promise.all([page.waitForURL('**/tasks?**project_id=**'), page.locator('.task-filter-form button[type="submit"]').click()]);
const filteredTotal = Number(await page.locator('.summary-card.all b').textContent());
if (filteredTotal >= unfilteredTotal) throw new Error('Task summary did not update after filtering');
await page.screenshot({ path: 'storage/app/task-filtered-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/tasks?due=today');
for (const dueDate of await page.locator('.task-reference-table tbody tr td:nth-child(7)').allTextContents()) {
    if (!dueDate.includes('18/08/2026')) throw new Error(`Today filter returned another date: ${dueDate}`);
}
await page.screenshot({ path: 'storage/app/task-today-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/tasks');
await page.locator('.summary-card.red').click();
await page.waitForURL('**/tasks?**overdue=1**');
await page.screenshot({ path: 'storage/app/task-overdue-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/tasks');
await page.locator('.action-menu-toggle').first().click();
await page.locator('.action-menu.open .action-menu-popover').waitFor({ state: 'visible' });
await page.waitForTimeout(200);
await page.screenshot({ path: 'storage/app/task-action-menu-current.png', fullPage: false });
await page.locator('[data-delete-action]').first().click();
await page.locator('#confirm-modal').waitFor({ state: 'visible' });
await page.screenshot({ path: 'storage/app/task-confirm-current.png', fullPage: false });
await page.locator('[data-confirm-cancel]').click();
await page.locator('a[href$="/tasks/create"]').first().click();
await page.waitForTimeout(250);
await page.screenshot({ path: 'storage/app/task-modal-current.png', fullPage: false });
await page.locator('#task-modal [data-modal-close]').first().click();
await page.locator('a[href$="/edit"]').first().click();
await page.locator('#task-modal').waitFor({ state: 'visible' });
await page.waitForTimeout(250);
await page.screenshot({ path: 'storage/app/task-edit-modal-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/projects');
await page.locator('a[href$="/projects/create"]').first().click();
await page.waitForTimeout(250);
await page.screenshot({ path: 'storage/app/project-modal-current.png', fullPage: false });
await browser.close();
