import { chromium } from 'playwright-core';

const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' });
const page = await browser.newPage({ viewport: { width: 1536, height: 1024 }, deviceScaleFactor: 1 });
await page.goto('http://127.0.0.1:8000/login');
await page.locator('input[name="email"]').fill('admin@taskwork.local');
await page.locator('input[name="password"]').fill('ChangeMe123!');
await Promise.all([page.waitForURL('**/dashboard'), page.locator('.login-submit').click()]);
for (const [name, path] of Object.entries({ dashboard: '/dashboard', 'task-cua-toi': '/my-tasks', 'tat-ca-task': '/tasks', 'du-an': '/projects', lich: '/calendar', 'bao-cao': '/reports', 'thanh-vien': '/members', nhan: '/labels', 'cai-dat': '/settings' })) {
    await page.goto(`http://127.0.0.1:8000${path}`);
    await page.screenshot({ path: `storage/app/${name}-current.png`, fullPage: false });
}
await page.goto('http://127.0.0.1:8000/tasks');
await page.locator('[data-filter-toggle]').click();
await page.locator('.task-filter-form.open').waitFor({ state: 'visible' });
await page.screenshot({ path: 'storage/app/task-filter-current.png', fullPage: false });
await page.locator('[data-filter-toggle]').click();
await page.locator('.summary-card.red').click();
await page.waitForURL('**/tasks?**overdue=1**');
await page.screenshot({ path: 'storage/app/task-overdue-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/tasks');
await page.locator('.action-menu-toggle').first().click();
await page.locator('.action-menu.open .action-menu-popover').waitFor({ state: 'visible' });
await page.waitForTimeout(200);
await page.screenshot({ path: 'storage/app/task-action-menu-current.png', fullPage: false });
await page.locator('[data-delete-action]').first().click();
await page.locator('#confirm-modal').waitFor({ state: 'visible' });
await page.screenshot({ path: 'storage/app/task-confirm-current.png', fullPage: false });
await page.locator('[data-confirm-cancel]').click();
await page.locator('a[href$="/tasks/create"]').first().click();
await page.waitForTimeout(250);
await page.screenshot({ path: 'storage/app/task-modal-current.png', fullPage: false });
await page.locator('#task-modal [data-modal-close]').first().click();
await page.locator('a[href$="/edit"]').first().click();
await page.locator('#task-modal').waitFor({ state: 'visible' });
await page.waitForTimeout(250);
await page.screenshot({ path: 'storage/app/task-edit-modal-current.png', fullPage: false });
await page.goto('http://127.0.0.1:8000/projects');
await page.locator('a[href$="/projects/create"]').first().click();
await page.waitForTimeout(250);
await page.screenshot({ path: 'storage/app/project-modal-current.png', fullPage: false });
await browser.close();
