@extends('layouts.app')
@section('title','Tất cả task · TaskFlow')
@section('heading')Tất cả task　<span class="heading-count">{{ $tasks->total() }}</span>@endsection
@section('actions')@endsection
@section('content')
<div class="task-toolbar"><div class="view-switch"><a class="icon-text {{ $viewMode==='list'?'active':'' }}" href="{{ route('tasks.index', array_merge(request()->except(['page','view']), ['view'=>'list'])) }}"><i data-lucide="list"></i>Danh sách</a><a class="icon-text {{ $viewMode==='kanban'?'active':'' }}" href="{{ route('tasks.index', array_merge(request()->except(['page','view']), ['view'=>'kanban'])) }}"><i data-lucide="columns-3"></i>Bảng Kanban</a><a class="icon-text" href="{{ route('calendar') }}"><i data-lucide="calendar-days"></i>Lịch</a><a class="icon-text {{ $viewMode==='gantt'?'active':'' }}" href="{{ route('tasks.index', array_merge(request()->except(['page','view']), ['view'=>'gantt'])) }}"><i data-lucide="git-branch"></i>Gantt</a></div><div class="task-toolbar-actions"><form class="task-search" method="get">@foreach(request()->except(['page','search']) as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach<label><i data-lucide="search"></i><input name="search" value="{{ request('search') }}" placeholder="Tìm kiếm task...">@if(request()->filled('search'))<a class="search-reset" href="{{ route('tasks.index', request()->except(['page','search'])) }}" title="Xóa tìm kiếm"><i data-lucide="x"></i></a>@endif</label><button class="btn secondary {{ request()->filled('project_id') || request()->filled('priority') || request()->filled('due') ? 'active' : '' }}" type="button" data-filter-toggle><i data-lucide="sliders-horizontal"></i>Bộ lọc</button></form><a class="btn primary task-create-button" href="{{ route('tasks.create') }}"><i data-lucide="plus"></i>Tạo task</a></div></div>
@include('tasks.partials.filters', ['action' => route('tasks.index')])
@if($viewMode === 'list')
<section class="task-data-card"><div class="task-summary">
    @foreach([['Tất cả',$statusCounts->sum(),null,'all'],['Việc cần làm',$statusCounts['todo']??0,'todo',''],['Đang thực hiện',$statusCounts['in_progress']??0,'in_progress','blue'],['Đang review',$statusCounts['review']??0,'review','orange'],['Hoàn thành',$statusCounts['done']??0,'done','green']] as [$label,$count,$status,$class])<a class="summary-card {{ $class }} {{ !request('overdue') && request('status')===$status ? 'active' : '' }}" href="{{ route('tasks.index', array_merge(request()->except(['page','status','overdue']), $status ? ['status'=>$status] : [])) }}"><span>{{ $label }}</span><b>{{ $count }}</b></a>@endforeach
    <a class="summary-card red {{ request()->boolean('overdue') ? 'active' : '' }}" href="{{ route('tasks.index', array_merge(request()->except(['page','status']), ['overdue'=>1])) }}"><span>Quá hạn</span><b>{{ $overdueCount }}</b></a>
    <form class="summary-actions" method="get">@foreach(request()->except(['page','sort']) as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach<label>Sắp xếp:<select name="sort" data-auto-submit>@foreach(['newest'=>'Mới nhất','oldest'=>'Cũ nhất','due_asc'=>'Hạn gần nhất','due_desc'=>'Hạn xa nhất','priority'=>'Ưu tiên cao'] as $value=>$label)<option value="{{ $value }}" @selected($sort===$value)>{{ $label }}</option>@endforeach</select></label><div class="action-menu"><button class="summary-icon-button action-menu-toggle" type="button" title="Xuất task" aria-label="Xuất task"><i data-lucide="download"></i></button><div class="action-menu-popover"><button type="button" data-export-table><i data-lucide="file-text"></i>Xuất CSV</button><a href="{{ route('tasks.export.weekly', request()->except(['page','view','sort','per_page'])) }}"><i data-lucide="sheet"></i>Weekly Report (.xlsx)</a></div></div><button class="summary-icon-button" type="button" data-density-toggle title="Thu gọn hàng"><i data-lucide="settings"></i></button></form>
</div>
<div class="task-reference-table"><table><thead><tr><th><input type="checkbox"></th><th>Task</th><th>Dự án</th><th>Người phụ trách</th><th>Nhãn</th><th>Ưu tiên</th><th>Hạn chót</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
@forelse($tasks as $task)<tr><td><input type="checkbox"></td><td><a class="task-title-link" href="{{ route('tasks.edit',$task) }}"><b>{{ $task->title }}</b>@if($task->id % 6)<span class="task-comments"><i data-lucide="message-square"></i>{{ $task->id % 6 }}</span>@endif</a></td><td><span class="project-cell"><i style="background:#{{ substr(md5($task->project->key),0,6) }}"></i>{{ $task->project->name }}</span></td><td><span class="person"><span class="avatar">{{ mb_substr($task->assignee?->name ?? '?',0,1) }}</span>{{ $task->assignee?->name ?? 'Chưa giao' }}</span></td><td><span class="task-label">{{ ['urgent'=>'Quan trọng','high'=>'UI/UX','medium'=>'Research','low'=>'Testing'][$task->priority] }}</span></td><td><span class="priority {{ $task->priority }}">{{ in_array($task->priority,['high','urgent'])?'↑':($task->priority==='low'?'↓':'−') }}　{{ ['urgent'=>'Khẩn cấp','high'=>'Cao','medium'=>'Trung bình','low'=>'Thấp'][$task->priority] }}</span></td><td class="{{ $task->due_date?->isPast()&&$task->status!=='done'?'text-danger':'' }}"><b>{{ $task->due_date?->format('d/m/Y') ?? '—' }}</b></td><td><span class="badge {{ $task->status }}">@if($task->status==='done')<i data-lucide="check"></i>@else<i class="status-dot"></i>@endif{{ ['todo'=>'Việc cần làm','in_progress'=>'Đang thực hiện','review'=>'Đang review','done'=>'Hoàn thành'][$task->status] }}</span></td><td>@include('tasks.partials.actions', ['task' => $task])</td></tr>@empty<tr><td colspan="9" class="empty">Chưa có task. Hãy chạy dữ liệu mẫu để hiển thị đầy đủ.</td></tr>@endforelse
</tbody></table></div>@include('tasks.partials.pagination', ['paginator'=>$tasks])</section>
@elseif($viewMode === 'kanban')
@include('tasks.partials.kanban')
@else
@include('tasks.partials.gantt')
@endif
@include('tasks.partials.modal')
@endsection
